# Generated by Django 5.2.4 on 2025-08-11 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_productimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(default=1, upload_to="product_images/"),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="ProductImage",
        ),
    ]
