# Generated by Django 5.2.4 on 2025-08-11 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_order_cancel_reason_order_is_cancelled_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProductImage",
        ),
    ]
